    <div class="navbar-wrapper">
      <div class="container">

        <div class="navbar navbar-inverse navbar-static-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html">Anticuisine</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="livre.html">Le livre</a></li>
                <li><a href="recettes.html">Les recettes</a></li>
                <li><a href="emission.html">L'émission</a></li>
                <li><a href="#">Les précurseurs</a></li>
                <li><a href="equipe.html">L'équipe</a></li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
