<div class="container">
  <footer>
  <div class="row">
    <div class="col-md-6">
      <p>&copy; anticuisine.fr par <a href="http://guilhem0.free.fr/" class="btn btn-default">Guilhem</a> &middot; Tous droits réservés</p>
    </div>
    <div class="col-md-6">
      <p>
        Suivez l'anticuisine sur&nbsp;: 
        <a class="btn btn-info" href="https://twitter.com/anticuisine">Twitter</a> 
        <a class="btn btn-primary" href="https://www.facebook.com/groups/anticuisine/">Facebook</a> 
        <a class="btn btn-danger" href="https://www.youtube.com/channel/UC3H_KE8s1SsfwuuKOZQgI7Q">Youtube</a>
      </p>
    </div>
  </div>
  </footer>
</div>
